version: ~> 1.0
os:
    - osx
osx_image: xcode12u

language: cpp
compiler:
    - clang

before_install:
    - pip3 install conan
      && conan config install https://vuo.org/sites/default/files/conan-macos.zip

install:
    - conan user

script:
    - conan create . vuo/stable
      && conan upload --remote vuo --all --no-overwrite all --confirm llvm/*
