os:
    - osx
osx_image: xcode6.4

language: cpp
compiler:
    - clang

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
             brew update
          && travis_wait brew install --force-bottle conan qbs
          && pushd .
          && cd $(mktemp -d -t apple-gcc42)
          && /usr/bin/curl -OL https://web.archive.org/web/20130512150329/https://r.research.att.com/tools/gcc-42-5666.3-darwin11.pkg
          && /usr/bin/xar -x -f gcc-42-5666.3-darwin11.pkg
          && /bin/pax -rz -f usr.pkg/Payload
          && mkdir -p /usr/local/Cellar/apple-gcc42
          && mv usr /usr/local/Cellar/apple-gcc42/4.2.1-5666.3
          && popd
          && ls -l /usr/lib/libgcc*
          && sudo ln -s libgcc_s.10.5.dylib /usr/lib/libgcc_s.10.4.dylib
      ; fi

install:
    - qbs setup-qt --detect
    - qbs setup-toolchains --detect
    - conan config install https://vuo.org/sites/default/files/conan-macos.zip
    - conan user

script:
    - conan create . vuo/stable
    - conan upload --remote vuo --all --confirm llvm/*
