matrix:
    include:
        # - os: osx
        #   osx_image: xcode7.3
        #   language: cpp
        #   compiler:
        #       - clang
        # - os: linux
        #   dist: trusty
        #   sudo: false
        #   language: python
        #   python: "3.6"
        #   addons:
        #       apt:
        #           sources:
        #               - llvm-toolchain-trusty-5.0
        #               - sourceline: 'ppa:beineri/opt-qt594-trusty'
        #           packages:
        #               - clang-5.0
        #               - libc++-dev
        #               - libc++1
        #               - libc++abi-dev
        #               - libc++abi1
        #               - qt59qbs
        - os: windows
          language: sh

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
             brew update &> /dev/null
          && travis_wait brew install --force-bottle conan qbs
          && conan config install https://vuo.org/sites/default/files/conan-macos.zip
      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
             pip install conan
          && conan config install https://vuo.org/sites/default/files/conan-linux.zip
          && . /opt/qt59/bin/qt59-env.sh
      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
             travis_wait choco install --no-progress python3 qbs
          && C:\\Python37\\Scripts\\pip install conan
          && ls -lR C:\\Python37
          && conan config install https://vuo.org/sites/default/files/conan-windows.zip
      ; fi

install:
    - qbs --version
    - qbs setup-qt --detect
    - qbs setup-toolchains --detect
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
             qbs config defaultProfile clang
      ; fi
    - conan user

script:
    - conan create . vuo/test
      && travis_wait conan upload --remote vuo --all --confirm llvm/*
