matrix:
    include:
        # - os: osx
        #   osx_image: xcode6.4
        #   language: cpp
        #   compiler:
        #       - clang
        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "3.6"
          addons:
              apt:
                  sources:
                      - llvm-toolchain-trusty-5.0
                      - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'
                  packages:
                      - clang-5.0
                      - qt510-meta-full

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
             brew update
          && travis_wait brew install --force-bottle conan qbs
          && sudo ln -s libSystem.B.dylib /usr/lib/libgcc_s.10.4.dylib
          && conan config install https://vuo.org/sites/default/files/conan-macos.zip
      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
             pip install conan
          && conan config install https://vuo.org/sites/default/files/conan-linux.zip
      ; fi

install:
    - ls -l /opt/qt510/bin
    - . /opt/qt510/bin/qt510-env.sh
    - apt-cache search .
    - qbs --version
    - qbs setup-qt --detect
    - qbs setup-toolchains --detect
    - conan user

script:
    - conan create . vuo/stable
      && conan upload --remote vuo --all --confirm llvm/*
