matrix:
    include:
        - os: osx
          osx_image: xcode7.3
          language: cpp
          compiler:
              - clang
        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "3.6"
          addons:
              apt:
                  sources:
                      - llvm-toolchain-trusty-5.0
                      - sourceline: 'ppa:beineri/opt-qt594-trusty'
                  packages:
                      - clang-5.0
                      - libc++-dev
                      - libc++1
                      - libc++abi-dev
                      - libc++abi1
                      - qt59qbs

cache:
    directories:
        - /usr/local/Cellar/conan
        - /usr/local/Cellar/gdbm
        - /usr/local/Cellar/libffi
        - /usr/local/Cellar/openssl
        - /usr/local/Cellar/pkg-config
        - /usr/local/Cellar/python
        - /usr/local/Cellar/readline
        - /usr/local/Cellar/sqlite
        - /usr/local/Cellar/xz
        - /usr/local/opt/python

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
             export HOMEBREW_NO_INSTALL_CLEANUP=1
          && brew update &> /dev/null
          && ( brew link libffi     || travis_wait brew install --force-bottle libffi     )
          && ( brew link openssl    || travis_wait brew install --force-bottle openssl    )
          && ( brew link xz         || travis_wait brew install --force-bottle xz         )
          && brew upgrade --force-bottle python
          && brew postinstall python
          && /usr/local/Cellar/python/3.7.4/bin/pip3 install setuptools
          && ( brew link conan      || travis_wait brew install --force-bottle conan      )
          && conan config install --source-folder vuo-conan https://vuo.org/sites/default/files/conan-macos.zip
      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
             pip install conan
          && conan config install --source-folder vuo-conan https://vuo.org/sites/default/files/conan-linux.zip
          && . /opt/qt59/bin/qt59-env.sh
          && qbs --version
          && qbs setup-qt --detect
          && qbs setup-toolchains --detect
          && qbs config defaultProfile clang
      ; fi

install:
    - conan user

script:
    - conan create -tf None . vuo/stable
      && travis_wait conan upload --remote vuo --all --confirm llvm/*
